In [2]:
import numpy as np

In [3]:
#TASK 1
array = np.random.random((10,3))

In [5]:
near = []
near = array[np.arange(10), np.abs(array-0.5).argmin(axis=1)]
print(array)
print(near)

[[0.52835215 0.19318289 0.89211951]
 [0.0446116  0.91336369 0.26587745]
 [0.25307315 0.8292712  0.15670901]
 [0.8745099  0.82375105 0.23477142]
 [0.63456839 0.15533936 0.90527606]
 [0.86788218 0.12000435 0.64840562]
 [0.35265385 0.72005902 0.87994785]
 [0.8556947  0.39768799 0.13867794]
 [0.25623223 0.77703768 0.4035858 ]
 [0.15194639 0.67370005 0.29826071]]
[0.52835215 0.26587745 0.25307315 0.23477142 0.63456839 0.64840562
 0.35265385 0.39768799 0.4035858  0.67370005]


In [6]:
# TASK 2
array = np.random.random((6,6))

In [33]:
res = []
s = array.sum(axis=1)
m = array.min(axis=0)
res = s/m
print(array)
print(res)

[[0.16645958 0.87337031 0.2659168  0.25888268 0.47120217 0.7577992 ]
 [0.97360474 0.17670226 0.18314878 0.13957465 0.74036281 0.46171055]
 [0.33478647 0.70729293 0.68309604 0.85888135 0.0846251  0.69992726]
 [0.08813503 0.50328052 0.241509   0.30889051 0.8158809  0.14128023]
 [0.24574767 0.16985733 0.86628171 0.23916109 0.27081368 0.68038335]
 [0.50659879 0.13047007 0.22224482 0.22781884 0.99204373 0.4414395 ]]
[31.69716605 20.50358246 18.39274653 15.03837698 29.21408471 17.84124912]


In [43]:
# TASK 3
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [49]:
mask = x==0
s = x[1:][mask[:-1]].max()
print(s)

5


In [6]:
# TASK 4
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x=np.array([i==j for j in range (10)]).sum(axis=1)+x
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [7]:
# TASK 5
a = np.arange(16).reshape(4, 4)
n = 4

In [160]:
d = {k: np.fliplr(a).diagonal(n-k-1) for k in range(2*n - 1)}

In [140]:
print(a)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
{0: array([0]), 1: array([1, 4]), 2: array([2, 5, 8]), 3: array([ 3,  6,  9, 12]), 4: array([ 7, 10, 13]), 5: array([11, 14]), 6: array([15])}


In [154]:
# TASK 6


In [11]:
def kmeans(a, k, s = 20, eps = 1e-05): 
    i = 0
    N = len(a[0]) 
    dim = len(a[1])
    centr = a[:k, :] 
    centr_tmp = np.zeros((k, dim))
    a = np.expand_dims(a, axis = 1) 
    d = dim * N * np.max(a)**2 
    d1 = 0
    
    while d1 - d > eps or i < s:
        d1 = d
        centr_tmp = centr
        
        numcentr = np.argmin(((a - centr) ** 2).sum(axis = 2), axis = 1) 
        C = np.zeros(N * k * dim).reshape(N, k, dim)
        C[np.arange(N), numcentr, :] = (a - centr)[np.arange(N),  numcentr, :] / np.bincount(numcentr)[numcentr].reshape(N, 1)
        centr = centr_tmp + np.squeeze(C.sum(axis = 0))        

        numcentr = np.argmin(((a - centr) ** 2).sum(axis = 2), axis = 1)
        C = np.zeros(N * k * dim).reshape(N, k, m)
        C[np.arange(N), numcentr, :] = (a - centr)[np.arange(N),  numcentr, :]
        d = np.sqrt((C ** 2).sum(axis = 2)).sum(axis = 1).mean()         
        i = i + 1
        
    return centr, d