In [5]:
import numpy as np

In [2]:
#TASK 1
array = np.random.random((10,3))

In [20]:
tmp = 1
near = []
for i in range(10):
    for j in array[i]:
        if abs(j-0.5) < (tmp-0.5) :
            tmp = j
    near.append(tmp)
    tmp = 1
print(array)
print(near)

[[0.83900748 0.54121124 0.84018996]
 [0.89495252 0.22497405 0.28164133]
 [0.78345577 0.30308617 0.69439507]
 [0.50094212 0.67472595 0.37200658]
 [0.95177975 0.09940406 0.47574512]
 [0.06660629 0.43597771 0.87437089]
 [0.71398013 0.13855342 0.94525491]
 [0.73063118 0.5426598  0.86696472]
 [0.03056596 0.83655753 0.75334456]
 [0.34058722 0.96551662 0.66621429]]
[0.5412112379585338, 0.22497405021792816, 0.3030861716427261, 0.5009421206183058, 0.09940405769659211, 0.06660629398697038, 0.7139801262873089, 0.5426597963108608, 0.030565960852674046, 0.34058722067600955]


In [23]:
# TASK 2
array = np.random.random((6,6))

In [27]:
res = []
tmp1 = 0
tmp2 = 1
for i in range(6):
    for k in range(6):
        if array[k, i] < tmp2:
            tmp2 = array[k,i]
    for j in array[i]:
        tmp1 += j
    res.append(tmp1/tmp2)
    tmp1 = 0
    tmp2 = 1
print(array)
print(res)

[[0.6512122  0.29858898 0.71666733 0.19050469 0.89716745 0.89920857]
 [0.04632988 0.15792298 0.33566192 0.50976086 0.27260874 0.9234981 ]
 [0.16406531 0.49700322 0.68592359 0.05745273 0.20556561 0.49919687]
 [0.82213127 0.88208132 0.62834964 0.08859564 0.54951572 0.73375988]
 [0.94674111 0.61633412 0.96826962 0.55233576 0.27665473 0.41762484]
 [0.94089147 0.99424407 0.31018017 0.24108996 0.4098378  0.79496511]]
[78.85514124117739, 14.22074532593069, 6.799942592408481, 64.477938044983, 18.37836720761933, 8.838575286939646]


In [28]:
# TASK 3
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [62]:
for i in range(len(x)-1):
    mask[i] = (x[i+1]==0)
m = -1e10
print mask
for i in x[mask]:
    if i>m:
        m = i
print(m)

[False  True False  True  True False False  True  True]
7


In [66]:
# TASK 4
x = np.ones(10)

i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j]+=1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [69]:
# TASK 5
a = np.arange(16).reshape(4, 4)
n = 4

In [152]:
d1={k: [a[i,k-i] for i in range(0,k+1)] for k in range(n)}
d2={k: [a[k-n+1+i,n-1-i] for i in range(0,2*n-k-1)] for k in range(n, 2*n-1)}
d1.update(d2)

In [153]:
print(d1)

{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}


In [154]:
# TASK 6


In [8]:
def kmeans(obs, k_or_guess, iter=20, thresh=1e-5):
    best_dist = np.inf
    No = obs.shape[0]
    k = k_or_guess
    for i in range(iter):
        guess = take(obs, randint(0, No, k), 0)
        book, dist = _kmeans(obs, guess, thresh=thresh)
        if dist < best_dist:
            best_book = book
            best_dist = dist
    result = best_book, best_dist
    return result